<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>CMakeLists.txt</string>
		<string>cmake</string>
	</array>
	<key>name</key>
	<string>CMakeEditor</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\$\{\w+\}</string>
			<key>name</key>
			<string>variable, storage</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(if|else|elseif|endif|foreach|break|endforeach|while|endwhile|function|endfunction|return|macro|endmacro|set)(?=\s*\()</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\w+)(?=\s*\()</string>
			<key>name</key>
			<string>meta.function-call, support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(build_name|exec_program|export_library_dependencies|install_files|install_programs|install_targets|link_libraries|make_directory|output_required_files|remove|subdir_depends|subdirs|use_mangled_mesa|utility_source|variable_requires|write_file)\b</string>
			<key>name</key>
			<string>invalid.deprecated</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#.+</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cmakeeditor</string>
	<key>uuid</key>
	<string>4e20e032-26f9-424c-9850-970835861de8</string>
</dict>
</plist>
